### PR TITLE
List dates for when everyone was/is principal developer.

### PR DESCRIPTION
**Pull request by bangerth**
I am missing @peterrum , @Rombur , @kronbichler .

I have no records apparently about Toby Young. Does anyone else?

### CODE REVIEW

**Comment by Rombur** [comment]
I have been a developer since 2013. I think it's the same for Toby Young.

**Comment by bangerth** [comment]
@Rombur Thanks. Do you happen to have a record until when he was a developer?

**Comment by bangerth** [comment]
Actually, I found it -- 2017.

**Comment by bangerth** [comment]
So only @peterrum and @kronbichler to go.

**Comment by kronbichler** [comment]
It's been 2013 for me as well.

**Comment by peterrum** [comment]
For me it is, 2020.

**Comment by bangerth** [comment]
Thanks. This is complete now.

**Review by kronbichler — APPROVED** [review]

**Pull request merged**
