### PR TITLE
add new contributors

### PR DESCRIPTION
**Pull request by tamiko**

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
Does this include the folks from the code gallery? Or only those who either had changelog entries or github PRs?

**Comment by tamiko** [comment]
@bangerth The latter.

**Comment by bangerth** [comment]
Should we also list folks who have contributed to the code gallery? Technically, the code gallery isn't part of the library. But in practice it is. I think it might be nice to do so. If you agree, I can do that.

**Comment by blaisb** [comment]
> Should we also list folks who have contributed to the code gallery? Technically, the code gallery isn't part of the library. But in practice it is. I think it might be nice to do so. If you agree, I can do that.

I think it's a good idea

**Comment by tjhei** [comment]
There is no harm in listing more contributors, so I agree.

**Pull request merged**
